version: "3.4"

x-common-variables: &common-variables
  DB_USER: ${DB_USER}
  DB_PASS: ${DB_PASS}
  DB : ${DB}
  REACT_APP_SERVER_PORT: ${REACT_APP_SERVER_PORT}

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      <<: *common-variables
      DB_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3309:3306
    restart: unless-stopped
    volumes:
      - ./db/db_comics.sql:/docker-entrypoint-initdb.d/db_comics.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: server_container
    depends_on:
      - mysql-db
    env_file:
      - ./server/.env
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 9000:9000
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: client_container
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
